<img height="60px" src="https://upload.wikimedia.org/wikipedia/commons/3/32/Emblem_of_Thammasat_University.svg" align="left" hspace="10px" vspace="0px">

# Data Basics and Introduction to Numpy

## การใช้งาน numpy เบื้องต้น

numpy เป็น library เอาไว้สร้างและจัดการชนิดข้อมูลแบบอาร์เรย์หลายมิติ (ndarray) ได้อย่างมีประสิทธิภาพ สามารถนำไปประยกุต์ใช้ใน data science ได้

---

**รหัสวิชา/ชื่อวิชา** IS461 Tools for Data Analytics ภาคเรียนที่ 1/66

**หลักสูตร** บริหารธุรกิจบัณฑิต คณะ พาณิชยศาสตร์และการบัญชี<br>
**ผู้สอน** จตุรพัชร์ พัฒนทรงศิวิไล



**cite:**
* https://github.com/numpy/numpy</li>
* https://colab.research.google.com/drive/1NQDtO3Y8kApxS5SwMPE2hvdUl3T_of4V</li>

# How to use Colab?

Colab พัฒนาโดย google เป็นหน้าเว็บเอาไว้ใช้เขียนโค้ด python ได้ผ่านทางหน้าเว็บ พร้อมทั้งเป็นเอกสารในตัว (เหมือนกับ Jupyter Notebook)

โดยหน้าเว็บจะเชื่อมต่อกับ  cloud service แถมยังเชื่อมต่อกับ google drive ของเราก็ได้ด้วย
พร้อมทั้งรองรับ GPU และ TPU
จึงเหมาะสำหรับงาน data science, machine learning, AI

**หมายเหตุ** <font color='blue'>**ต้องมี Gmail**</font> ถึงจะรันหน้า colab ได้ และสามารถแก้ไขโค้ดได้ แต่**ไฟล์จะไม่ถูก save**

<h3>สามารถแก้ไข และรันได้</h3>
<img height="200px" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/use_Colab3.png" align="center" hspace="10px" vspace="0px">


---

<h3>ถ้าจะแก้ไขและ save ได้ด้วย ต้อง copy ไฟล์ .ipynb ไปที่่ google drive ของเราเสียก่อน ดังนี้</h3>

<h3>กด Copy to Drive ... เพื่อบันทึกไว้ google drive เครื่องเรา</h3>

<img height="200px" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/use_Colab1.png" align="center" hspace="10px" vspace="0px">



<h3>จากนั้นไฟล์ .ipynb จะบันทึกที่ Google Drive ของเรา</h3>

<img height="200px" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/use_Colab2.png" align="center" hspace="10px" vspace="0px">

---

<h3>แต่ถ้าเราไม่มี Gmail ดาวน์โหลดไฟล์ .ipynb แล้วนำไปเปิดที่ Jupyter Notebook ในเครื่องของเรา </h3>


<img height="500px" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/use_Colab4.png" align="center" hspace="10px" vspace="0px">

# Data Basics

<table>
  <tr>
    <th>Name</th>
    <th>Web page</th>
    <th>Data types</th>
  </tr>
  <tr>
    <td>UCI</td>
    <td><a href="https://archive.ics.uci.edu/ml/index.php">link</a></td>
    <td>Data for machine learning</td>
  </tr>
  <tr>
    <td>WHO</td>
    <td><a href="https://www.who.int/en">link</a></td>
    <td>Healthcare data</td>
  </tr>
  <tr>
    <td>Amazon Web Service</td>
    <td><a href="https://registry.opendata.aws/">link</a></td>
    <td>Web usage</td>
  </tr>
    <tr>
    <td>US Government Open Data</td>
    <td><a href="https://www.data.gov/">link</a></td>
    <td>Agriculture, climate, consumer, and so on</td>
  </tr>
  <tr>
    <td>Github</td>
    <td><a href="https://github.com/awesomedata/awesome-public-datasets">link</a></td>
    <td>Many datasets offered by individuals</td>
  </tr>
  <tr>
    <td>Open data network</td>
    <td><a href="https://www.opendatanetwork.com/">link</a></td>
    <td>Many useful datasets</td>
  </tr>
  <tr>
    <td>Government health data</td>
    <td><a href="https://healthdata.gov/">link</a></td>
    <td>Healthcare-related datasets</td>
  </tr>
  <tr>
    <td>Google public data</td>
    <td><a href="https://www.google.com/publicdata/directory">link</a></td>
    <td>World development indicators</td>
  </tr>
  <tr>
    <td>Kaggle</td>
    <td><a href="https://www.kaggle.com/datasets">link</a></td>
    <td>Open datasets and Machine Learning Project</td>
  </tr>
  <tr>
    <td>Federal reserve economic data</td>
    <td><a href="https://www.federalreserve.gov/datadownload/">link</a></td>
    <td>Data related to selected Federal Reserve Board statistical releases</td>
  </tr>
  <tr>
    <td>Census bureau</td>
    <td><a href="https://www.census.gov/about/index.html">link</a></td>
    <td>Census data</td>
  </tr>
  <tr>
    <td>US. dept. treasure</td>
    <td><a href="https://home.treasury.gov/">link</a></td>
    <td>US treasure yield</td>
  </tr>
  <tr>
    <td>Bureau of labor statistics</td>
    <td><a href="https://www.bls.gov/">link</a></td>
    <td>Inflation, employment, unemployment, pay and benefits, and so on</td>
  </tr>
  <tr>
    <td>Bureau of economic analysis</td>
    <td><a href="https://www.bea.gov/">link</a></td>
    <td>GDP, personal income outlays, corporate profit, and so on</td>
  </tr>
  <tr>
    <td>National bureau of economic research</td>
    <td><a href="https://www.nber.org/">link</a></td>
    <td>Business cycles, vital statistics, reports of presidents, and so on</td>
  </tr>
  <tr>
    <td>Yahoo! Finance</td>
    <td><a href="https://finance.yahoo.com/">link</a></td>
    <td>Historical pricing data, options, balance sheets, and income statements</td>
  </tr>
  <tr>
    <td>Google Finance</td>
    <td><a href="https://www.google.com/finance/">link</a></td>
    <td>Current and historical trading prices</td>
  </tr>
  <tr>
    <td>Marketwatch</td>
    <td><a href="https://www.marketwatch.com/">link</a></td>
    <td>Financial statements</td>
  </tr>
  <tr>
    <td>SEC filing</td>
    <td><a href="https://www.sec.gov/edgar.shtml">link</a></td>
    <td>Balance sheets, income statements, holdings, and so on</td>
  </tr>
  <tr>
    <td>Professor French's data library</td>
    <td><a href="https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html">link</a></td>
    <td>Fama/French factors, market index, risk-free rate, industry classification, and so on</td>
  </tr>
</table>

# Installation of NumPy

คำสั่งติดตั้งโมดูล ถ้าไปที่ command line บนเครื่องตัวเอง
ให้พิมพ์คำสั่งดังนี้<br>
**pip install numpy**

<font color='red'>*ปกติแล้ว ถ้าลง Anaconda
หรือใช้งาน colab
ไม่ต้องพิมพ์คำสั่งดังกล่าว*</font>

# Import NumPy

<font color="green"><strong>ต้องนำเข้า Numpy ก่อน ถึงจะใช้งานได้</strong></font>

<strong>** คำเตือน</strong> <font color="red"> ถ้าหน้าเว็บ Colab มัน timeout (ถูกตัดขาดการเชื่อมต่อ) ก็ต้องกลับมากดรันโค้ดนี้ใหม่ด้วย</font>

หรือเราจะไปที่ Runtime -> เลือก "Run all" (คีย์ลัด Ctrl+F9)
เพื่อรันหน้านี้ใหม่ทั้งหมด

หรือจะวางประโยคคำสั่ง import numpy as np ก่อนประโยคคำสั่งอื่นๆ ในทุกๆ cells

In [ ]:
import numpy as np

# Numpy Tutorial
* NumPy Creating Arrays
* NumPy Array Indexing
* NumPy Array Slicing
* NumPy Data Types
* NumPy Array Shape
* NumPy Array Reshaping
* NumPy Joining Array
* NumPy Splitting Array
* NumPy Searching Arrays
* NumPy Sorting Arrays
* NumPy Filter Array

# NumPy Creating Arrays

สร้างอาร์เรย์หลายมิติ (ndarray) จากชนิดข้อมูล list, tuple, array-like object โดยใช้ numpy

**หมายเหตุ**  อาร์เรย์ใน numpy เรียกว่า **<font color="blue">ndarray</font>**

ชนิดข้อมูลใน python ที่รองรับโครงสร้างข้อมูลแบบอาร์เรย์ ก็คือ list กับ tuple

* ชนิดข้อมูล list ใน python จะเป็นอาร์เรย์ขยายขนาดได้ และแก้ไขได้
* ส่วนชนิดข้อมูล tuple ใน python จะเป็นอาร์เรย์ที่สร้างขึ้นมาแล้ว จะแก้ไขอะไรไม่ได้

* ซึ่งชนิดข้อมูลพวกนี้มีข้อจำกัดบางประการ ไม่สะดวกต่อการนำไปใช้ในงาน data science ด้วยเหตุนี้ numpy จึงกำหนดชนิดข้อมูล ndarray ขึ้นมา  เป็นอาร์เรย์หลายมิติ เพื่อให้ช่วยจัดการได้ง่ายขึ้น

ตัวอย่าง
* ตัวอย่าง list ใน python เช่น [1, 2, 3, 4, 5]
* ตัวอย่าง tuple ใน python เช่น (1, 2, 3, 4, 5)

In [ ]:
# ตัวอย่าง list ใน pyhton
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [ ]:
# ตัวอย่าง tuple ใน python
(1, 2, 3, 4, 5)

(1, 2, 3, 4, 5)

**สร้าง ndarray ด้วยฟังก์ชัน array()**

<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_1-dimension.png">

In [ ]:
np.array( [1, 2, 3, 4, 5] ) # สร้าง ndarray จาก list
np.array( [1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.array( (1, 2, 3, 4, 5) )  # สร้าง ndarray จาก tuple

array([1, 2, 3, 4, 5])

**สามารถมีสมาชิกใน ndarray ไม่ต้องเป็นตัวเลขเสมอไป**

In [ ]:
np.array(['ant', 'bat', 'cat', 'dog', 'elephant']) # สมาชิกข้างในเป็น string

array(['ant', 'bat', 'cat', 'dog', 'elephant'], dtype='<U8')

In [ ]:
np.array([True, False, False, True]) # สมาชิกข้างในเป็น boolean

array([ True, False, False,  True])

**กำหนดค่าของ ndarray ให้กับตัวแปรมาอ้างอิง**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
#print(arr)

**ดูชนิดข้อมูล** โดยใช้ฟังก์ชัน type()

In [ ]:
type( np.array([1, 2, 3, 4, 5]) )

numpy.ndarray

## ndim กับ shape


<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarray_is_object.png">




**ดูมิติ (dimension)** โดยใช้แอตทริบิวต์ ndim




In [ ]:
np.array([1, 2, 3, 4, 5]).ndim

1

**ดูรูปร่าง (shape)** โดยใช้แอตทริบิวต์ shape จะรีเทิร์นข้อมูลออกมาในรูป tuple

In [ ]:
np.array([1, 2, 3, 4, 5]).shape # มีสมาชิก 5 ตัว มี shape เป็น (5,)

(5,)

## ข้อควรรู้ Shape

index ของ shape ใน ndarray จะเรียกว่า axis (แกน) เป็นการบอกตำแหน่งของแกนมิติ

**ตัวอย่าง ndadrray มีขนาด 1 มิติ โดยมี shape เป็น (5,)**

ในกรณีนี้

* axis หมายเลข 0 มีความยาวเป็น 5

<img width="15%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/shape_axis_1d.png">
<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_1-dimension.png">

---

**ตัวอย่าง ndadrray มีขนาด 2 มิติ โดยมี shape เป็น (2, 3)**

ในกรณีนี้

* axis หมายเลข 0 มีความยาวเป็น 2
* axis หมายเลข 1 มีความยาวเป็น 3

<img width="20%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/shape_axis_2d.png">
<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_2-dimension.png">

---

**ตัวอย่าง ndadrray มีขนาด 3 มิติ โดยมี shape เป็น (2, 3, 4)**


ในกรณีนี้

* axis หมายเลข 0 มีความยาวเป็น 2
* axis หมายเลข 1 มีความยาวเป็น 3
* axis หมายเลข 2 มีความยาวเป็น 4

<img width="23%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/shape_axis_3d.png">
<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_3-dimension.png">

# Data Types in NumPy




## dtype attribute

ฟังก์ชัน type() ต้องการดูว่าอาร์เรย์เป็นชนิดข้อมูล ndarray หรือไม่

แต่ถ้าจะดูชนิดข้อมูลของสมาชิกภายใน ndarray ก็ให้ใช้แอตทริบิวต์ dtype

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.dtype) # int64 -- integer 64 bits

arr2 = np.array(['ant', 'bat', 'cat', 'dog', 'elephant']) # unicode string -- 8 characters
print(arr2.dtype) # <U8

arr3 = np.array(['ขาว', 'แดง', 'ดำ']) # unicode string -- 3 characters
print(arr3.dtype) # <U3

int64
<U8
<U3


## Creating Arrays With a Defined Data Type <font color="red">(เสริมเพิ่มเติม)</font>

**สามารถระบุชนิดข้อมูลของสมาชิก ตั้งแต่เริ่มต้นสร้าง ndarray**

โดยจะมีตัวอักษรที่สื่อถึงชนิดข้อมูล ดังนี้

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype='i4') # integer 4 bytes (8*4 = 32 bits)
#arr = np.array([1, 2, 3, 4, 5], dtype='i') # default is 32 bits or 'i4'
#arr = np.array([1, 2, 3, 4, 5], dtype='i8') # integer 4 bytes (8*8 = 64 bits)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


แปลงชนิดข้อมูลของสมาชิกภายใน ndarray ตั้งแต่ตอนสร้าง ndarray ครั้งแรก

In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype='S') # แปลงชนิดข้อมูลจาก int32 เป็น string
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


## Converting Data Type on Existing Arrays <font color="red">(เสริมเพิ่มเติม)</font>

ใช้ฟังก์ชัน astype()

In [ ]:
arr = np.array([1.1, 2.1, 3.1]) # float
newarr = arr.astype('i') # integer -- default 32 bits or 'i4'

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


อีกทางเลือกหนึ่ง

In [ ]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int) # integer 64 bits
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


**ตัวอย่าง** แปลงตัวเลขเป็น boolean
 * ถ้าเป็นเลข 0 จะแปลงเป็น False
 * ถ้าไม่ใช่เลข 0 จะแปลงเป็น True

In [ ]:
arr = np.array([1, 0, -3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


**หมายเหตุ** <font color="red">ถ้าแปลงชนิดข้อมูลไม่ได้ NumPy จะเกิด (ValueError)</font>

# Creating Multi-dimensional array

Dimensions in Arrays

* 0-D Arrays
* 1-D Arrays เปรียบได้เป็น ตารางแถวเดียว
* 2-D Arrays เปรียบได้เป็น ตารางที่มีทั้งแถว และคอลัมน์
* 3-D arrays เปรียบได้เป็น ตารางที่ซ่อนกันหลายชั้น
* n-D arrays

## 0-D Arrays

ndarray ขนาด 0 มิติ จะเป็น scalar หรือเลขจำนวนค่าหนึ่ง

In [ ]:
arr = np.array(1)
print(arr)
print('number of dimensions :', arr.ndim)
print('shape :', arr.shape)

1
number of dimensions : 0
shape : ()


## 1-D Arrays

<p>ตัวอย่าง ndarray ขนาด 1 มิติ</p>
<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_1-dimension.png?raw=true">

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('number of dimensions :', arr.ndim)
print('shape :', arr.shape)

[1 2 3 4 5]
number of dimensions : 1
shape : (5,)


## 2-D Arrays

ndarray 2 มิติ ก็คืออาร์เรย์ 1 มิติ ที่ซ้อนอยู่ในอีกอาร์เรย์หนึ่ง
สามารถใช้แทน matrix หรือตารางได้

<p>ตัวอย่างอาร์เรย์ขนาด 2 มิติ ซึ่งจะมี shape = (2, 3)</p>

ถ้าเปรียบ ndarray 2 มิติ เป็นตาราง
* axis 0 ก็คือ แถว
* axis 1 ก็คือ คอลัมน์

ดังนั้น shape = (2, 3) ก็จะประกอบด้วย
* มี 2 แถว
* มี 3 คอลัมน์

<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_2-dimension.png">



In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)
print('number of dimensions :', arr.ndim)
print('shape :', arr.shape)

[[1 2 3]
 [4 5 6]]
number of dimensions : 2
shape : (2, 3)


## 3-D Arrays

ndarray 3 มิติ ก็คืออาร์เรย์ 2 มิติ ที่ซ้อนอยู่ในอีกอาร์เรย์หนึ่ง สามารถใช้แทน tensor 3 มิติ

<p>ตัวอย่างอาร์เรย์ขนาด 3 มิติ ซึ่งจะมี shape = (2, 3, 4)</p>

ถ้าเปรียบ ndarray 3 มิติ เป็นตาราง ก็จะเป็นตารางที่ซ้อนกัน
* axis 0 ก็คือ จำนวนตารางที่ซ้อนกัน
* axis 1 ก็คือ แถว
* axis 2 ก็คือ คอลัมน์

ดังนั้น shape = (2, 3, 4) ก็จะประกอบด้วย
* จำนวนตาราง 2 อัน
* แต่ละตารางมี 3 แถว
* แต่ละตารางมี 4 คอลัมน์

<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarry_3-dimension.png">





In [ ]:
arr = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print(arr)
print('number of dimensions :', arr.ndim)
print('shape :', arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
number of dimensions : 3
shape : (2, 3, 4)


## Higher Dimensional Arrays <font color="red">(เสริมเพิ่มเติม)</font>

ตอนสร้างอาร์เรย์ สามารถกำหนดมิติเท่าไรได้

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr)
print('number of dimensions :', arr.ndim)
print('shape :', arr.shape)

[[1 2 3 4]]
number of dimensions : 2
shape : (1, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
print('shape :', arr.shape)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
shape : (1, 1, 1, 1, 4)


# สร้าง ndarray จากฟังก์ชัน

สามารถสร้าง ndarray ด้วยการะบุ shape (tuple) พร้อมด้วยการระบุสมาชิกตั้งต้นให้

**ฟังก์ชัน zeros()** จะระบุค่าของสมาชิกทุกตัวใน ndarray เป็นศูนย์หมด

In [ ]:
np.zeros( (5) )    # shape (5) สมาชิกจะเป็นเลข 0 หมด -- 1 มิติ

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 3))    # shape (2, 3) สมาชิกจะเป็นเลข 0 หมด -- 2 มิติ

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 4)) # (2, 3, 4) สมาชิกเป็นเลข 0 หมด -- 3 มิติ

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

**ฟังก์ชัน ones()** จะระบุค่าของสมาชิกทุกตัวใน ndarray เป็น 1 หมด

In [ ]:
np.ones((5))     # shape (5) สมาชิกจะเป็นเลข 1 หมด -- 1 มิติ

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 3))     # shape (2, 3) สมาชิกจะเป็นเลข 1 หมด -- 2 มิติ

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2, 3, 4)) # (2, 3, 4) สมาชิกเป็นเลข 1 หมด -- 3 มิติ

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

**ฟังก์ชัน full()** จะระบุค่าของสมาชิกทุกตัวใน ndarray เป็นค่าอะไรก็ได้ (ค่าเดียวเหมือนกันหมด)

In [ ]:
np.full( (5), 1.1)   # shape = (5) สมาชิกเป็น 1.1 หมด -- 1 มิติ

array([1.1, 1.1, 1.1, 1.1, 1.1])

In [ ]:
np.full( (4, 5), 3.2)   # shape = (4, 5) สมาชิกเป็น 3.2 หมด -- 2 มิติ

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [ ]:
np.full((2, 3, 4), 0.7) # shape = (2, 3, 4) สมาชิกเป็นเลข 0.7 หมด -- 3 มิติ

array([[[0.7, 0.7, 0.7, 0.7],
        [0.7, 0.7, 0.7, 0.7],
        [0.7, 0.7, 0.7, 0.7]],

       [[0.7, 0.7, 0.7, 0.7],
        [0.7, 0.7, 0.7, 0.7],
        [0.7, 0.7, 0.7, 0.7]]])

:**สร้างสมาชิกใน ndarry 1 มิติ แบบเพิมค่าขึ้นไปเรื่อยๆ ด้วยฟังก์ชัน arange()**

In [ ]:
np.arange(5) # สร้าง ndarray 1 มิติ เริ่มตั้งแต่ 0 แต่ยังไม่ถึง 5 (สมาชิก 5 ตัว)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5, 10) # สร้าง ndarray 1 มิติ เริ่มตั้งแต่เลข 5 แต่ยังไม่ถึง 10 (เพิ่มทีละ 1 ค่า)

array([5, 6, 7, 8, 9])

**สามารถระบุ step ได้ด้วย**

In [ ]:
np.arange(0, 10, 2) # เริ่มตั้งแต่เลข 0 เพิ่มไปที่ละ 2 ค่า แต่ยังไม่ถึง 10

array([0, 2, 4, 6, 8])

**หรือจะสร้างสมาชิกแบบลดค่าลงไปเรื่อยๆ ก็ได้ โดยใช้ step เป็นค่าติดลบ**

In [ ]:
np.arange(10, 5, -1) # เริ่มจาก 10 ลดไปทีละ -1 แต่ยังไม่ถึง 5

array([10,  9,  8,  7,  6])

**ฟังก์ชัน linspace()** สร้างสมาชิกโดยมีค่าอยู่ระหว่างช่วงข้อมูล

In [ ]:
# สร้าง ndarray 1 มิติ เลขระหว่าง 0 ถึง 1 โดยจะมีสมาชิก 4 ตัว
np.linspace(0, 5, 4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

## สร้างสมาชิกใน ndarray แบบ random <font color="red">(เสริมเพิ่มเติม)</font>

In [ ]:
# ใช้ฟังก์ชัน normal
mean = 10
stdev = 3    # Standard deviation
number_values = 20
np.random.normal(mean, stdev, number_values) # normal (Gaussian) distribution

array([10.80413169,  8.53060886, 15.63964316,  9.85226606,  9.56324619,
        7.52640172, 12.22258656,  5.14684044, 11.49176273,  9.31487439,
        5.67795405,  8.89317395, 11.28722899, 10.32047921,  9.94172365,
       13.30076544,  8.07560788, 10.38519345, 12.20825879,  1.46240553])

In [ ]:
# ใช้ฟังก์ชัน randint
np.random.randint(0, 10, 20) # สุ่มค่าตั้งแต่ 0 เป็นต้นไป แต่ยังไม่ถึง 10 ( 0 <= N < 10) มีจำนวนสมาชิก 20 ตัว

array([5, 5, 9, 4, 8, 9, 6, 9, 2, 0, 9, 2, 7, 5, 4, 8, 3, 3, 5, 1])

In [ ]:
# ใช้ฟังก์ชัน permutation
np.random.permutation(20) # สร้างเลข 0 เป็นต้นไป แต่ยังไม่ถึง 20 ( 0 <= N < 20) -- พร้อมจัดเรียงสับเปลี่ยนลำดับอัตโนมัติ (รันแต่ละครั้งลำดับไม่เหมือนเดิม)

array([19, 10, 12,  2,  3,  7, 17, 18, 15,  9, 13,  8, 14,  1,  6, 16,  0,
       11,  5,  4])

In [ ]:
# สับเปลี่ยนอาร์เรย์
np.random.permutation([1, 2, 3, 4, 5])

array([5, 3, 1, 2, 4])

# Reshape

โดยใช้เมธอด reshape() แล้วได้เป็น **ndarray ตัวใหม่** ที่มี shape เปลี่ยนไป

## Reshape From 1-D to 2-D

**ข้อควรระวัง** <font color="red">ถ้าปรับขนาดที่ไม่เหมาะสมจะเกิด error (จำนวนสมาชิกเกินมาหรือขาดไม่ได้)</font>

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(4, 3) # แถว=4, คอลัมน์=3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Reshape From 1-D to 3-D

**ข้อควรระวัง** <font color="red">ถ้าปรับขนาดที่ไม่เหมาะสมจะเกิด error (จำนวนสมาชิกเกินมาหรือขาดไม่ได้)</font>

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
arr.reshape(2, 3, 4) # จำนวนตาราง=2, แถว=3, คอลัมน์=4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Unknown Dimension

ถ้าไม่รู้ขนาดแกน ก็ให้ใส่ -1 เพื่อให้ reshape คำนวณความยาวให้อัตโนมัติ

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = arr.reshape(2, 2, -1)
print(new_arr)
print('shape :', new_arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape : (2, 2, 2)


## ตัวอย่างอื่นๆ

**ตัวอย่าง** แปลง ndarray จาก shape (2, 3) ไปเป็น (3, 2) และ (6, 1)

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50 ,60]])
print("Before reshape")
print(arr)
print("After reshape to (3, 2)")
new_arr = arr.reshape(3, 2)
print(new_arr)
print("After reshape to (6, 1)")
new_arr = arr.reshape(6, 1)
print(new_arr)

Before reshape
[[10 20 30]
 [40 50 60]]
After reshape to (3, 2)
[[10 20]
 [30 40]
 [50 60]]
After reshape to (6, 1)
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


**ตัวอย่าง** แปลง ndarrray จาก shape (2, 3, 4) ไปเป็น (3, 2, 4)

In [ ]:
arr = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print("Before reshape")
print(arr)
print('shape :', arr.shape)
print("After reshape to (3, 2, 4)")
new_arr = arr.reshape(3, 2, 4)
print(new_arr)

Before reshape
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape : (2, 3, 4)
After reshape to (3, 2, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


## Flattening the arrays

เราสามารถจับ ndarray ที่มีหลายมิติ มายืดออก ให้เหลือ 1 มิติ ด้วยการระบุค่า -1 ส่งไปให้ฟังก์ชัน reshape()

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

# Access Array Elements (1-D)



## อ่านและแก้ไขค่าสมาชิกใน ndarray ทีละตัว

สามารถเข้าถึงสมาชิกแต่ละตัวใน ndarray ด้วยวงเล็บเหลี่ยมเปิดและปิด ([...])
และข้างในวงเหล็บเหลี่ยมจะระบุ index เพื่อบอกตำแหน่งของแต่ละสมาชิก

ลองพิจารณาตัวอย่าง

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/negative_index.png">

**อ่านค่าใน ndarray**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[3]) # อินเดกซ์เป็นบวก
print(arr[-2]) # อินเดกซ์เป็นลบ

40
40


**แก้ไขสมาชิกใน ndarray**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2] = 300
arr[-2] = 400
print(arr)

[ 10  20 300 400  50]


## Slicing

Slicing คือการตัดเฉือนสมาชิก ตามช่วงที่ระบุ

**รูปแบบการใช้งาน**
* arr[<strong><font color="orange">start</font>:<font color="blue">end</font></strong>]
* arr[<strong><font color="orange">start</font>:<font color="blue">end</font>:<font color="green">step</font></strong>]

การตัดเฉือนสมาชิกใน ndarray จะเริ่มจากตำแหน่ง start แต่ยังไม่ถึง end โดยนับเพิ่มขึ้นทีละ step **(ได้เป็น ndarray ตัวใหม่ออกมา)**

**โดยดีฟอลต์**
* ถ้าไม่ระบุ startจะมีค่าเป็น 0
* ถ้าไม่ระบุ end จะมีค่าเป็นความยาวของมิตินั้นๆ
* ถ้าไม่ระบุ step จะมีค่าเป็น 1 (เพิ่มขึ้นที่ละหนึ่ง)

**ตัวอย่างการทำ slicing**

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/slicing_index.png">

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[4:])  # เสมือนเขียน arr[4:5]
print(arr[:4])  # เสมือนเขียน arr[0:4]

[20 30 40]
[50]
[10 20 30 40]


**ตัวอย่างการทำ slicing โดยใช้ index เป็นค่าลบ**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-4:-1])
print(arr[-1:5])  # เสมือนเขียนเป็น arr[-1:5]
print(arr[0:-1])  # เสมือนเขียนเป็น arr[0:-1]

[20 30 40]
[50]
[10 20 30 40]


### การระบุ Step ตอนทำ slicing

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/slicing_index.png">

**ตัวอย่างการทำ slicing เพิ่มทีละสเตป (ค่าบวก)**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[::2] # slicing มาห่างกันทีละ 2 อินเด็กซ์ เสมือนเขียน arr[0:5:2]

array([10, 30, 50])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[0:3:2] # slicing เริ่มที่อินเด็กซ์ start=0 (ยังไม่ถึงอินเด็กซ์ end=3) และเพิ่มทีละ 2 อินเด็กซ์

array([10, 30])

**สามารถมี step เป็นค่าติดลบ เพื่อประยุกต์ reverse ย้อนกลับหลังได้**






<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/slicing_index.png">

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[::-1] # ขยับลดทีละ -1 อินเด็กซ์ จากหลังไปหน้า เสมือนเขียน arr[0:5:-1]

array([50, 40, 30, 20, 10])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[::-2] # ขยับลดทีละ -2 อินเด็กซ์ จากหลังไปหน้า เสมือนเขียน arr[0:5:-2]

array([50, 30, 10])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# ถ้า start > end
# ดู start กับ end ตรงตำแหน่ง index โดยตรง
arr[4:2:-1] # ตำแหน่งเริ่มต้นอินเด็กซ์ start=4 ไล่ย้อนมา (ยังไม่ถึงอินเดกซ์ end=2 )โดยลดทีละ -1 อินเด็กซ์

array([50, 40])

**ข้อสังเกต ถ้า slicing โดยใช้ : หมายถึงเข้าถึงสมาชิกทั้งหมดในแกนนั้นๆ**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print( arr[:] ) # เสมือนเขียน arr[0:5]
print( arr[::1] ) # เสมือนเขียน arr[0:5:1]

[10 20 30 40 50]
[10 20 30 40 50]


## อ่านและแก้ไขค่าสมาชิกใน ndarray เป็นช่วงข้อมูล

โดยสามารถนำการ slicing มาประยุกต์ใช้ได้ เพื่อแก้ไขข้อมูล ในช่วงข้อมูลใดข้อมูลหนึ่ง

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/slicing_index.png">

**แก้ไขบางช่วงของ ndarray**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2:4] = -100
print(arr)

[  10   20 -100 -100   50]


**แก้ไขข้อมูลทั้งหมดใน ndarray ให้มีค่าเดียวกันหมด**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[:] = 255 # ห้ามเขียน arr = 255
print(arr)

[255 255 255 255 255]


**ข้อสังเกต การแก้ไขข้อมูลใน ndarray ทั้งชุด**

ต้อง slicing มาทั้งหมดก่อน แล้วถึงอัปเดตทีหลัง
เพราะถ้าเขียน arr = 255
จะเป็นการเปลี่ยนให้ arr ชี้ไปยังตัวเลข 255 ไม่ใช่ np.array([10, 20, 30, 40, 50])

# Access Array Elements (2-D)





**เข้าถึงสมาชิกที่ละตัว โดยใช้วงเล็บเหลี่ยมเปิดและปิด ([...])**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/Access_Array_Elements_2-D.png">

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
print(arr[1, 2])

# เข้าถึงอินเด็กซ์เป็นลบ
print(arr[-2,-3])

80
30


**สามารถทำ slicing ก็ได้ (ได้เป็น ndarray ตัวใหม่ออกมา)**

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/Access_Array_Elements_2-D_slicing.png">


In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[70 80 90]
[30 80]
[[20 30 40]
 [70 80 90]]


**หรือจะ slice โดยระบุ step**

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
arr[::2, ::2] # เสมือนเขียน arr[0:2:2, 0:5:2]

array([[10, 30, 50]])



**เข้าถึงแค่มิติแรกอย่างเดียวก็ได้ (เข้าถึงแถวอย่างเดียว)**

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
print(arr[1]) # เข้าถึงแถว ตรง index = 1
print(arr[-2]) # เข้าถึงแถว ตรง index = -2
print(arr[1:2]) # เข้าถึงแถว โดยการทำ slicing เป็น 1:2

[ 60  70  80  90 100]
[10 20 30 40 50]
[[ 60  70  80  90 100]]


**slicing โดยใช้ : เพื่อเข้าถึงสมาชิกทุกตัวในแกนนั้นๆ**

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
print(arr[1, :]) # เสมือนเขียน arr[1, 0:5] หรือ arr[1]

[ 60  70  80  90 100]


**ประยุกต์ใช้ slicing เพื่อเข้าถึงข้อมูลเป็นช่วง แล้วแก้ไขให้มีค่าเดียวกัน**

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/Access_Array_Elements_2-D_slicing.png">

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
arr[:, 1:3] = -1  # เสมือนเขียน arr[0:2, 1:3] = -1
print(arr)

[[ 10  -1  -1  40  50]
 [ 60  -1  -1  90 100]]


**หรือจะเลือกเข้าถึงแค่มิติแรก (เข้าถึงแถว) แล้วแก้ไขทั้งแถว ให้มีค่าเดียวกันหมด**

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
arr[1] = 3 # เข้าถึงแถวตรง index = 1
print(arr)

[[10 20 30 40 50]
 [ 3  3  3  3  3]]


**แก้ไขค่าทั้งหมดใน ndarray ให้มีค่าเดียวกันหมด**

In [ ]:
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100]])
arr[:] = 1 # เสมือนเขียน arr[0:2] = 1 (เข้าถึงทุกแถวในอาร์เรย์ แล้วกำหนดค่าให้กับสมาชิกทุกตัวเป็น 1 หมดในคราวเดียวกัน)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]]


**ข้อสังเกต การแก้ไขข้อมูลใน ndarray ทั้งชุด**

ต้อง slicing มาทั้งหมดก่อน แล้วถึงอัปเดตทีหลัง
เพราะถ้าเขียน arr = 1
จะเป็นการเปลี่ยนให้ arr ชี้ไปยังตัวเลข 1 ไม่ใช่ ndarray

# Access Array Elements (3-D) <font color="red">(เสริมเพิ่มเติม)</font>

**ตัวอย่างใช้** เครื่องหมาย : เพื่อทำการ slicing เข้าถึงทั้งมิตินั้นๆ

In [ ]:
x = np.array( [
                [[1, 2, 3],
                 [4, 5 ,6],
                 [7, 8, 9]],

                [[11, 12, 13],
                 [14, 15 ,16],
                 [17, 18, 19]]
              ]
             )

print("shape = ", x.shape)
print( x[1, : , :])
print( x[:, 2 , :])
print( x[:, : , 0])

shape =  (2, 3, 3)
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 7  8  9]
 [17 18 19]]
[[ 1  4  7]
 [11 14 17]]


แก้ไขค่าทั้งหมด โดยระบุช่วงข้อมูลที่ต้องการ (ใช้ slicing)

In [ ]:
x[0:1, : , :] = 72
x

array([[[72, 72, 72],
        [72, 72, 72],
        [72, 72, 72]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [ ]:
x[:, 0:1 , :] = 255
x

array([[[255, 255, 255],
        [ 72,  72,  72],
        [ 72,  72,  72]],

       [[255, 255, 255],
        [ 14,  15,  16],
        [ 17,  18,  19]]])

In [ ]:
x [:, :, 1:3] = -10
x

array([[[255, -10, -10],
        [ 72, -10, -10],
        [ 72, -10, -10]],

       [[255, -10, -10],
        [ 14, -10, -10],
        [ 17, -10, -10]]])

หรือจะเปลี่ยนค่าของสมาชิกทุกตัวในคราวเดียวกัน

In [ ]:
x[:, :, :] = -333 # ห้ามเขียน x = 333
print(x)
x[:] = 222 # ห้ามเขียน x = 22
print(x)

[[[-333 -333 -333]
  [-333 -333 -333]
  [-333 -333 -333]]

 [[-333 -333 -333]
  [-333 -333 -333]
  [-333 -333 -333]]]
[[[222 222 222]
  [222 222 222]
  [222 222 222]]

 [[222 222 222]
  [222 222 222]
  [222 222 222]]]


# เข้าถึงสมาชิกใน ndarray หลายๆ ค่า ด้วยการระบุ index หลายๆ ค่า (indices)

โดยภายในเครื่องหมายวงเล็บเหลี่ยมเปิดและปิด ([...]) จะกำหนดให้มี list ของ
index ต่างๆ (จะมีวงเหล็บเหลี่ยมเปิดและปิดซ้อนกันสองชั้น) เพื่อกรองเอาสมาชิกที่ต้องการออกมา **(ได้เป็น ndarray ตัวใหม่ออกมา)**

**ตัวอย่าง**

<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarray_many_indices.png">

In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])
arr[[0, 2, 4]]

array([10, 30, 50])

**ระบุอินเด็กซ์โดยใช้ ndarray ก็ได้**

In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])
indices = np.array([0, 2, 4])
arr[indices] # arr[[0, 2, 4]]
arr[[0, 2, 4]]

array([10, 30, 50])

**ไม่ต้องเรียงลำดับก็ได้**

In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])
arr[[4, 2, 0]]

array([50, 30, 10])

**นำไปประยุกต์จัดเรียงตำแหน่งใหม่ แบบย้อนหลัง (reverse)**





In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])
arr[[4, 3, 2, 1, 0]] # หรือจะเขียนเป็น arr[::-1]

array([50, 40, 30, 20, 10])

**ระบุอินเด็กซ์ติดลบก็ได้ด้วย**

In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])
arr[[0, -2, -1]]

array([10, 40, 50])

# คัดเลือกสมาชิกใน ndarray ด้วยการระบุเป็น Boolean ก็ได้

โดยภายในเครื่องหมายวงเล็บเหลี่ยม ([...]) จะกำหนดให้มี list ของ Boolean เพื่อกรองเอาสมาชิกที่ต้องการออกมา  **(ได้เป็น ndarray ใหม่ออกมา)**


**ตัวอย่าง**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/ndarray_many_indices_boolean.png">

**ข้อสังเกต** จำนวน Boolean ต้องเท่ากับจำนวนสมาชิกใน ndarray

In [ ]:
arr = np.array([10 , 20 , 30 , 40 , 50])
arr[[True, False, True, False, True]] # เลือกสมาชิกที่ตำแหน่งตรงกัน True

array([10, 30, 50])

# นำ ndarray มาเปรียบเทียบกับ scalar

นำสมาชิกทุกตัวใน ndarray มาเปรียบเทียบกับ scalar **ได้เป็น ndarray ตัวใหม่** ที่มีสมาชิกเป็น boolean (True หรือ False)



**ตัวอย่าง**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/compare_ndarray_equal.png">

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
arr == 4  # นำสมาชิกทุกตัวมาเปรียบเทียบ ได้เป็น ndarray ของ boolean

array([False, False, False,  True, False,  True,  True])

**ตัวอย่าง**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/compare_ndarray_greater_than.png">



In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
arr > 3 # นำสมาชิกทุกตัวมาเปรียบเทียบ ได้เป็น ndarray ของ boolean

array([False, False, False,  True,  True,  True,  True])

**ตัวอย่าง**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/compare_ndarray_not_equal.png">

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
arr != 4 # นำสมาชิกทุกตัวมาเปรียบเทียบ ได้เป็นอาร์เรย์ของ boolean

array([ True,  True,  True, False,  True, False, False])

## ค้นหาสมาชิกใน ndarry ตามเงื่อนไขเปรียบเทียบ

**ตัวอย่าง**

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/NumPy_Searching_Arrays_with_conditons.png">

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 40, 40])
#print(arr== 4) # [False, False, False, True, False, True, True]

arr[arr==40]  # เสมือนเขียน arr[[False, False, False, True, False, True, True]]

array([40, 40, 40])

**ใช้ฟังก์ชัน where() เพื่อรีเทิร์นตำแหน่ง indexes ออกมา**

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 40, 40])
#print(arr== 4) # [False, False, False, True, False, True, True]

np.where(arr == 40) # เสมือนเขียน np.where([False, False, False, True, False, True, True])

(array([3, 5, 6]),)

## ตัวอย่าง ทำการค้นหาโดยใช้เงื่อนไขที่ซับซ้อนขึ้น <font color="red">(เสริมเพิ่มเติม)</font>



**ตัวอย่าง**

<img width="80%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/NumPy_Searching_Arrays_with_conditons_complex.png">

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[(arr>5) & (arr!=7)]

array([6])

# ดำเนินการทางคณิตศาสตร์

**ตัวอย่าง scalar คูณกับ ndarray**

In [ ]:
x = np.array([1, 2, 3, 4, 5])
-10*x

array([-10, -20, -30, -40, -50])

ใส่ค่าติดลบ

In [ ]:
x = np.array([1, 2, 3, 4, 5])
-x

array([-1, -2, -3, -4, -5])

**ตัวอย่าง scalar บวกกับ ndarray**

In [ ]:
x = np.array([1, 2, 3, 4, 5])
x + 10

array([11, 12, 13, 14, 15])

**นำสมาชิกใน ndarray มายกกำลัง**

In [ ]:
x = np.array([1, 2, 3, 4, 5])
x**2

array([ 1,  4,  9, 16, 25])

**ตัวอย่างอาร์เรย์ กับ อาร์เรย์ นำมาบวก หรือลบกัน (ตำแหน่งต่อตำแหน่ง)**

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a + b)
print(a - b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]


**ตัวอย่างอาร์เรย์ กับ อาร์เรย์ นำมาคูณ หรือหารกัน (ตำแหน่งต่อตำแหน่ง)**

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a * b)
print(a / b)

[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


**สามารถกระทำทางคณิตศาสตร์ กับ ndarray หลายมิติก็ได้ด้วย**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/operator_with_ndarray_complex.png">

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

ans = a/4 + 3*b
print(ans)

[[15.25 18.5 ]
 [21.75 25.  ]]


# Joining NumPy Arrays <font color="red">(เสริมเพิ่มเติม)</font>

รวม 2 ndarray เข้าด้วยกัน

ภายหลังการรวมกันแล้ว shape เปลี่ยน



**ตัวอย่างใช้ฟังก์ชัน concatenate() กับ ndarray 1-D**

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

**ตัวอย่าง** ndarray ขนาด 2-D มารวมกัน โดย **axis=0** จะหมายถึงนำคอลัมน์มาต่อกัน

<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/stack_vstack.png">

In [ ]:
arr1 = np.array([[1, 2],
                [3, 4]])
arr2 = np.array([[5, 6],
                [7, 8]])

np.concatenate((arr1, arr2), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**ตัวอย่าง** ndarray ขนาด 2-D มารวมกัน โดย **axis=1** (เป็นค่า default) จะหมายถึงนำแถวมาต่อกัน

<img width="60%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/stack_hstack.png">

In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**ตัวอย่างฟังก์ชัน vstack()**

จะคล้ายๆ np.concatenate(tup, axis=1) เป็นการนำคอลัมน์มาต่อกัน


In [ ]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**ตัวอย่างฟังก์ชัน hstack()**

จะคล้ายๆ np.concatenate(tup, axis=0) เป็นการนำแถวมาต่อกัน

In [ ]:
arr1 = np.array([[1, 2],
                         [3, 4]])
arr2 = np.array([[5, 6],
                         [7, 8]])
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

**ตัวอย่างฟังก์ชัน stack()** <font color="red">(เสริมเพิ่มเติม)</font>

ภายหลังการใช้ stack() เพื่อรวมกันของสอง ndarray แล้ว นอกจาก shape เปลี่ยนแล้ว มิติก็เพิ่มขึ้น (แกน axis เพิ่มขึ้นมา)

ต่อกันตามแกน axis=0 แล้วคำนวณ shape ใหม่ พร้อมจัดเรียงใหม่

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.shape)
print(arr2.shape)

new_arr = np.stack((arr1, arr2), axis=0)
print(new_arr.shape)
print(new_arr)

(3,)
(3,)
(2, 3)
[[1 2 3]
 [4 5 6]]


ต่อกันตามแกน axis=1 แล้วคำนวณ shape ใหม่ พร้อมจัดเรียงใหม่

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.shape)
print(arr2.shape)

new_arr = np.stack((arr1, arr2), axis=1)
print(new_arr.shape)
print(new_arr)

(3,)
(3,)
(3, 2)
[[1 4]
 [2 5]
 [3 6]]


**ตัวอย่าง dstack()** <font color="red">(เสริมเพิ่มเติม)</font>

รวมกันแล้ว เพิ่มมิติแนวลึก แล้วคำนวณ shape ใหม่ พร้อมจัดเรียงใหม่

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
new_arr = np.dstack((arr1, arr2))
print(new_arr.shape)
print(new_arr)


(1, 3, 2)
[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays <font color="red">(เสริมเพิ่มเติม)</font>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

**แบ่ง 1-D ndarray**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


**แบ่ง 2-D ndarray**

In [ ]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arr, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# NumPy Searching Arrays <font color="red">(เสริมเพิ่มเติม)</font>



## Search Sorted

ฟังก์ชั่น searchsorted() ใช้ในการค้นหา ผลลัพธ์จะรีเทิร์นตำแหน่ง index ของสมาชิกที่พบเจอครั้งแรก

**หมายเหตุ** จะทำการค้นหาในอาร์เรย์ที่สมาชิกถูกจัดเรียงลำดับเท่านั้น ซึ่งอัลกอริทึมที่ใช้เป็น binary serach ในการค้นหา


In [ ]:
arr = np.array([6, 7, 8, 9]) # สมาชิกถูกเรียงลำดับ
np.searchsorted(arr, 7) # found 7 at index 1

1

ข้อมูลต้องถูกจัดเรียงตามลำดับก่อน ถ้าไม่เรียงต้องจัดเรียงลำดับ

In [ ]:
arr = np.array([9, 7, 8, 6])
arr_sorted = np.sort(arr) # ต้องเรียงลำดับก่อน
print(arr_sorted)
np.searchsorted(arr_sorted, 7) # found 7 at index 1

[6 7 8 9]


1

## Search From the Right Side

โดย default จะค้นหาจากซ้ายไปขวา
รีเทิร์น index ของสมาชิกตัวเแรกที่เจอ

ดังตัวอย่าง

<img width="40%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/Search_From_the_Right_Side.png">

In [ ]:
arr = np.array([6, 7, 7, 9])
np.searchsorted(arr, 7) # found 7 at index 1

1

แต่เราก็สามารถค้นหาจากขวาไปซ้ายก่อนได้

In [ ]:
arr = np.array([6, 7, 7, 9])
np.searchsorted(arr, 7,side='right') # # found 7 at index 3

3

# Sorting Arrays <font color="red">(เสริมเพิ่มเติม)</font>

จัดเรียงสมาชิกใน ndarray

## Sorting a 1-D Array

**เรียงจากน้อยที่สุด ไปหามากที่สุด (ascending order)**

In [ ]:
arr = np.array([3, -2, 0, 1, 5, -4])
np.sort(arr)

array([-4, -2,  0,  1,  3,  5])

**สมาชิกที่เป็นชนิดข้อมูลอื่น ก็ถูกจัดเรียงได้ ไม่ใช่แค่ตัวเลข**

In [ ]:
arr = np.array(['watermelon', 'apple','orange', 'papaya', 'banana', 'strawberry'])
print(np.sort(arr))

['apple' 'banana' 'orange' 'papaya' 'strawberry' 'watermelon']


**จัดเรียงจากมากที่สุด ไปหาน้อยที่สุด (decreasing order)**

นำฟังก์ชัน flip() มากลับด้านข้อมูล

In [ ]:
arr = np.array([3, -2, 0, 1, 5, -4])
arr_asc = np.sort(arr)  # ให้จัดเรียงจากน้อยที่สุด ไปหามากที่สุด เสียก่อน
np.flip(arr_asc) # แล้วค่อยกลับด้าน

array([ 5,  3,  1,  0, -2, -4])

**หรือจะใช้เทคนิค slicing เข้าช่วย เพื่อ reverse ย้อนกลับ**

In [ ]:
arr = np.array([3, -2, 0, 1, 5, -4])
np.sort(arr)[::-1]

array([ 5,  3,  1,  0, -2, -4])

**ข้อควรระวัง np.sort()**

เวลาจัดเรียง ไม่ได้แก้ไขค่าใน ndarray ตัวต้นฉบับ
แต่จะรีเทิร์น ndarray ตัวใหม่ที่ถูกจัดเรียงออกมาแล้ว

In [ ]:
arr = np.array([3, -2, 0, 1, 5, -4])
arr_sorted = np.sort(arr)
print("Before sorted:" ,arr)
print("After sorted:" ,arr_sorted)

Before sorted: [ 3 -2  0  1  5 -4]
After sorted: [-4 -2  0  1  3  5]


## Sorting a 2-D Array

In [ ]:
arr = np.array([[3, 2, 4],
                [5, 6, 1]])
print("Before sorted");
print(arr)
print("After sorted");
print(np.sort(arr))    # default axis = -1

Before sorted
[[3 2 4]
 [5 6 1]]
After sorted
[[2 3 4]
 [1 5 6]]


**การระบุ axis**

* axis = 0 จัดเรียงตามแกน axis = 0
* axis = 1 จัดเรียงตามแกน axis = 1

โดย default แล้ว axis = -1 หมายถึง axis ตัวสุดท้าย

ดังนั้นในกรณี 2-D array ค่า default ก็คือ axis = 1

**ลองพิจารณาตัวอย่าง**

<img width="50%" src="https://raw.githubusercontent.com/adminho/machine-learning/master/images/Sorting_2-D_Array_with_axis.png">

In [ ]:
arr = np.array([[9, 6, 4],
                [5, 8, 1],
                [3, 2, 7]])

print("After sorting with axis=0");
print(np.sort(arr, axis=0))

print("After sorting with axis=1");
print(np.sort(arr, axis=1))

After sorting with axis=0
[[3 2 1]
 [5 6 4]
 [9 8 7]]
After sorting with axis=1
[[4 6 9]
 [1 5 8]
 [2 3 7]]


# ตัวอย่างฟังก์ชันที่เป็น Utility ใน numpy <font color="red">(เสริมเพิ่มเติม)</font>

In [ ]:
x = np.array([[10, 20] ,
              [30, 40] ,
              [50 ,60], [70, 80]])
print(x)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [ ]:
x.min() # หาค่าน้อยที่สุด

10

In [ ]:
x.max() # หาค่ามากที่สุด

80

In [ ]:
x.cumsum() # บวกค่าแบบสะสมไปเรื่อยๆ

array([ 10,  30,  60, 100, 150, 210, 280, 360])

In [ ]:
x.cumprod() # คูณค่าแบบสะสมไปเรื่อยๆ

array([           10,           200,          6000,        240000,
            12000000,     720000000,   50400000000, 4032000000000])

คำนวณทางคณิตศาสตร์ทั้ง ndarray

In [ ]:
import numpy as np
x = np.arange(10)
np.sin(x)
np.cos(x)
np.tanh(x)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

# ใน numpy มีฟังก์ชันใช้งานกับ list ได้ <font color="red">(เสริมเพิ่มเติม)</font>

In [ ]:
x = [[10, 20] , [30, 40] , [50 ,60], [70, 80]]
np.shape(x) # ดูรูปร่างของ list

(4, 2)

In [ ]:
np.min(x)  # หาค่าน้อยที่สุด

10

In [ ]:
np.max(x)  # หาค่ามากที่สุด

80

In [ ]:
np.cumsum(x) # บวกค่าแบบสะสมไปเรื่อยๆ

array([ 10,  30,  60, 100, 150, 210, 280, 360])

In [ ]:
np.cumprod(x) # คูณค่าแบบสะสมไปเรื่อยๆ

array([           10,           200,          6000,        240000,
            12000000,     720000000,   50400000000, 4032000000000])

# ทิ้งท้าย

สามารถใช้ฟังก์ชั่น savetxt() บันทึกข้อมูลลงเป็นไฟล์ csv ก็ได้

In [ ]:
import numpy as np
arr = np.full((100,100), 3.2)
np.savetxt('test.csv', arr, fmt="%f", delimiter=',')


สามารถใช้ฟังก์ชั่น savetxt() อ่านข้อมูลจากไฟล์ csv กลับคืนมา


In [ ]:
arr = np.loadtxt('test.csv',delimiter=',')
arr

array([[3.2, 3.2, 3.2, ..., 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, ..., 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, ..., 3.2, 3.2, 3.2],
       ...,
       [3.2, 3.2, 3.2, ..., 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, ..., 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, ..., 3.2, 3.2, 3.2]])

เนื่องจากเวลาเราใช้ numpy จะต้องสร้างข้อมูล โดยระบุค่าของตัวเลขเอง
ถ้ามีเป็นพันเป็นหมื่นข้อมูล จะยุ่งยาก  เราไม่สามารถคีย์ข้อมูลจำนวนเยอะมากได้
รวมทั้งอ่านและเขียนข้อมูลเก็บไว้ลงไฟล์ อาจทำไม่ได้สะดวกมากนัก

จึงต้องมีวิธีอ่านข้อมูลที่เก็บอยู่ในไฟล์ โดยจะใช้ไลบรารี่ pandas ซึ่งจะสะดวกกว่า

คอร์สถัดไป
[Pandas](https://colab.research.google.com/drive/1yjwcJYm3KChjBnl6jo4qsrdbPoGKRXzE)

In [ ]:
import pandas as pd
df = pd.read_csv('https://www.w3schools.com/python/pandas/data.csv')
arr = df.values
print(arr)
print(arr.shape)

[[  60.   110.   130.   409.1]
 [  60.   117.   145.   479. ]
 [  60.   103.   135.   340. ]
 [  45.   109.   175.   282.4]
 [  45.   117.   148.   406. ]
 [  60.   102.   127.   300. ]
 [  60.   110.   136.   374. ]
 [  45.   104.   134.   253.3]
 [  30.   109.   133.   195.1]
 [  60.    98.   124.   269. ]
 [  60.   103.   147.   329.3]
 [  60.   100.   120.   250.7]
 [  60.   106.   128.   345.3]
 [  60.   104.   132.   379.3]
 [  60.    98.   123.   275. ]
 [  60.    98.   120.   215.2]
 [  60.   100.   120.   300. ]
 [  45.    90.   112.     nan]
 [  60.   103.   123.   323. ]
 [  45.    97.   125.   243. ]
 [  60.   108.   131.   364.2]
 [  45.   100.   119.   282. ]
 [  60.   130.   101.   300. ]
 [  45.   105.   132.   246. ]
 [  60.   102.   126.   334.5]
 [  60.   100.   120.   250. ]
 [  60.    92.   118.   241. ]
 [  60.   103.   132.     nan]
 [  60.   100.   132.   280. ]
 [  60.   102.   129.   380.3]
 [  60.    92.   115.   243. ]
 [  45.    90.   112.   180.1]
 [  60. 

# ลิงก์เอกสารชุดนี้

* https://colab.research.google.com/drive/1VYaRGqAtJ3uw1G5LTw60jRaCNMR2LDXU?usp=sharing



